### ISSUE TITLE
Custom nginx.conf not applied

### ISSUE THREAD

**Issue by abrain** [DO1JLR/ansible_role_nginx#2]
The generated nginx.conf is written to `/etc/nginx/nginx.conf.j2` instead of `/etc/nginx/nginx.conf`. That way the default config from the package remains unchanged.

https://github.com/DO1JLR/ansible_role_nginx/blob/955cf7c6c825f4c0039bf71eae0f0138c9ea3ecd/tasks/nginx.yml#L2-L6

**Comment by DO1JLR** [comment]
oh, right
